name: Auto NIC packager

on:
  push:
    branches:
    - main
    - template/*

jobs:
  packager:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Theos
      run: |
        sudo apt-get install fakeroot git perl clang build-essential -y
        echo "export THEOS=~/theos" >> ~/.profile
        source ~/.profile
        git clone --recursive https://github.com/theos/theos.git $THEOS
        
        curl https://kabiroberai.com/toolchain/download.php?toolchain=ios-linux -Lo toolchain.tar.gz
        tar xzf toolchain.tar.gz -C $THEOS/toolchain
        rm toolchain.tar.gz
        
        curl -LO https://github.com/theos/sdks/archive/master.zip
        TMP=$(mktemp -d)
        unzip master.zip -d $TMP
        mv $TMP/sdks-master/*.sdk $THEOS/sdks
        rm -r master.zip $TMP

    - name: Get version
      run: echo "VERSION=$(cat ./template/versionCheck.sh | sed -n 2p | tail -c 7 | head -c 5)" >> $GITHUB_ENV

    - name: Debug Environment
      run: |
        echo "VERSION=${{ env.VERSION }}"
        ls -l

    - name: Make NIC package
      run: |
        source ~/.profile
        rm ./Ted2's Mod Menu Template v${{ env.VERSION }}.nic.tar || true
        $THEOS/bin/nicify.pl ./template

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: "Ted2's Mod Menu Template v${{ env.VERSION }}.nic.tar"
        path: "./Ted2's Mod Menu Template v${{ env.VERSION }}.nic.tar"

    - name: Create Release
      id: create-release
      uses: actions/create-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        body: ""
        draft: false
        prerelease: false

    - name: Add Package to release
      uses: actions/upload-release-asset@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: "./Ted2's Mod Menu Template v${{ env.VERSION }}.nic.tar"
        asset_name: "Ted2-Mod-Menu-Template v${{ env.VERSION }}.nic.tar"
        asset_content_type: application/x-tar
